name: mining-world
version: @version@
main: etiocook.miningworld.MiningWorld
authors: [eTioCooK]
load: STARTUP
softdepend:
  - "Multiverse-Core"
commands:
  mining:
    aliases:
      - mina
      - mine
      - minerar
